### ISSUE TITLE
LocalDatePicker and multiple selection

### ISSUE THREAD

**Issue by r-taseen** [JFXtras/jfxtras#19]
Hi, just continuing my bug report thread here since I think it's more appropriate than at StackExchange.
I tried the 8.0-r4-SNAPSHOT (from 01/30/2015) with scene builder and multiple selection on LocalDatePicker is still not functional for me.
Again, CalendarPicker works fine.

**Comment by tbee** [comment]
I will react on StackExchange once we figured out why it is not working.

Because, yes, it is working for me; the reason for the problem was clear and was fixed. However, what I experienced is that SceneBuilder keeps a folder with external libraries. Adding a new one through the application does not remove the old. So I manually cleaned out dead wood from that folder, if you are on windows it is in c:<user>\AppData\Roaming\Scene Builder\Library. Attached are the only two files in my library folder, just so you can verify it works, because the date of what you downloaded is correct.

To "prove" it is working, below a screenshot of SceneBuilder with both a CalendarPicker and LocalDatePicker (see hierarchy) and the preview both with a selection in multiple mode.

**Comment by tbee** [comment]
Oh boy, I had not seen that I was replying to a GitHub issue email.

![2015-02-01 08 04 16](https://cloud.githubusercontent.com/assets/1429698/5991360/b601254a-a9e9-11e4-9d6e-c21e72619861.png)

**Comment by tbee** [comment]
And the jars:
http://www.softworks.nl/stuff/jfxtras-common-8.0-r4-SNAPSHOT.jar
http://www.softworks.nl/stuff/jfxtras-controls-8.0-r4-SNAPSHOT.jar

**Comment by r-taseen** [comment]
I was previously already replacing the scene builder library manually for importing controls.
It seems the .jar files you provided (the 01/02/2015 version of the snapshot) fixed the problem:
https://oss.sonatype.org/content/repositories/snapshots/org/jfxtras/jfxtras-controls/8.0-r4-SNAPSHOT/jfxtras-controls-8.0-r4-20150201.090120-115.jar
https://oss.sonatype.org/content/repositories/snapshots/org/jfxtras/jfxtras-common/8.0-r4-SNAPSHOT/jfxtras-common-8.0-r4-20150201.090112-115.jar

You can reproduce the problem using the 31/01/2015 version or less on sonatype, which I was using before:
https://oss.sonatype.org/content/repositories/snapshots/org/jfxtras/jfxtras-common/8.0-r4-SNAPSHOT/jfxtras-common-8.0-r4-20150131.090111-114.jar
https://oss.sonatype.org/content/repositories/snapshots/org/jfxtras/jfxtras-controls/8.0-r4-SNAPSHOT/jfxtras-controls-8.0-r4-20150131.090119-114.jar
In any case, fixed! Thanks

**Comment by tbee** [comment]
That are the nightly's, I'll push out the sources again, something went wrong building those I guess. Would you mind accepting the answer at StackExchange, so other will find it.
