### ISSUE TITLE
TEST FAILED

### ISSUE THREAD

**Issue by redmetro1** [JFXtras/jfxtras#65]
Hi, 

I am new to JAVA and I want to try jfxtras. I downloaded jfxras and I followed the instruction for Windows CMD, "gradlew assemble." and I got the build successful. Now, I did "gredlew build" and I got all 13 tests failed. I tried it on netbeans and got the same errors. 
I am using Windows 10, gradle 2.13 and jdk1.8.0_91. 
I've also set JAVA6_HOME to jdk1.6.0_45 and JAVA_HOME to jdk1.7.0_79. 

Again, I am new to all this and have no idea. I really appreciate it if somebody can help me. 

Thanks, 

[testfailed.txt](https://github.com/JFXtras/jfxtras/files/265167/testfailed.txt)

**Comment by tbee** [comment]
The error says "Unsupported major.minor version 51.0", so you are not using the correct JDK. It seems you are using JSE 6, because 51 is JSE7 (https://en.wikipedia.org/wiki/Java_class_file). But where did you get instructions to set these environment variables?

**Comment by redmetro1** [comment]
If I don't set JAVA6_HOME or JAVA7_HOME, I get the following error and telling me to set them. 

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':jfxtras-agenda:test'.
  
  > When running gradle with java 8, you must set the path to the old jdk, either with property retrolambda.oldJdk or environment variable JAVA5_HOME/JAVA6_HOME/JAVA7_HOME
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by tbee** [comment]
Interesting indeed. I get the same. The reason is that the test framework (TestFX) could not easily run headless on a Jenkins server. So I run the UI tests manually prior to releasing. That has changed fairly recently, but I didn't have the time to modify the project yet. 

That means that the tests never get run in the way you are doing it, but only directly from the IDE. Apparently adding Retrolambda (in order to make JFXtras run on Android) has broken the ability to run the test as part of the gradle build cycle, but I never found that. 

For now, build using "-x test" and I'll see what retrolambda is doing there.

**Comment by tbee** [comment]
The problem most likely related to that JavaFX is not included in JSE6.

**Comment by redmetro1** [comment]
Also, there is nothing in generated JAR file under build\libs. 
Is this the JAR file I need to include in my own project in order to use jfxtras?

[jfxtras-all-8.0-r5-SNAPSHOT.zip](https://github.com/JFXtras/jfxtras/files/266461/jfxtras-all-8.0-r5-SNAPSHOT.zip)

**Comment by tbee** [comment]
JFXtras consist of a few jars as described on jfxtras.org, you should select the ones you need. The latest SNAPSHOT versions are in Sonatype's snapshot repository. There is no need to compile them yourself.
https://oss.sonatype.org/content/repositories/snapshots/org/jfxtras/

**Comment by tbee** [comment]
So. I removed the "all" artifact from the build process, we no longer use that. It was there for backward compatibility with the first JFXtras release. And Gradle is not cooperating to generate it.

Retrolambda indeed required java 6 or 7 to run the test, but that won't work, because JavaFX is either not present or different from the Java 8 version. But I can easily trick retrolambda in still using Java 8 to run the tests.

**Comment by tbee** [comment]
closed because of no response
