### ISSUE TITLE
TestFX upgrade

### ISSUE THREAD

**Issue by Maxoudela** [JFXtras/jfxtras#76]
Hi,

I'm wondering if we could try to upgrade the TestFX version to at least 4.0 ? Or is there any reasons we should not?

My keyboard is in French, and each time I run the JFXtras tests, the tests are failing because I need to put my keyboard in QWERTY otherwise the input are wrong. Also my mouse settings are put back to default. 

These issues are currently fixed from 4.0 TestFX version. Also, the tests can be ran in HeadLess mode which is very nice because you can actually do something else when the tests are running (and you even can run them in a device that hasn't any screen).

Honestly, I don't know the amount of work to do the migration, but since I'm using TestFX 4.0 in my application, I think I can do it without too much difficulty..

**Comment by tbee** [comment]
I've been holding this off unit 4.0 was out officially, because I have quite a number of tests and have a lot of tuning in the tests cases. But yes, it is on my todo list. But having to choose between working on ResponsivePane and upgrading TestFX. Well... ;-)

**Comment by Maxoudela** [comment]
What is Responsivepane..? 

Honestly, I've seen what are in the tests, but most of the things you implemented in your test cases are in TestFX. If not, maybe it would be great adding them into TestFX directly. If you need them, there's some chance others will need it too no?

**Comment by tbee** [comment]
Yes, yes, it should be doable. The author of TestFX warned me that it would be quite a bit of work. But let's give it a shot.

**Comment by tbee** [comment]
ResponsivePane is my attempt to do responsive layout, by having a layout that automatically chooses the best fitting one, and also by replacing CSS files based on screen width. It turned out that the implementation by GUI Garage did not work on mobile. I've written some blogs about that.

I'm still in the middle of it all, but the current state looks like this:
https://github.com/JFXtras/jfxtras-labs/blob/8.0/src/test/resources/jfxtras/labs/scene/layout/ResponsivePaneFXMLDemo.fxml

**Comment by tbee** [comment]
TestFX 4.x is being used
